backend:
  name: git-gateway
  branch: master

media_folder: static/img/uploads
public_folder: /img

collections:
  - name: 'words'
    label: 'Words'
    format: 'json'
    folder: 'content/words'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:      
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Published', name: 'date', widget: 'datetime' }
      - { label: 'Last Updated', name: 'updated', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Content', name: 'content', widget: 'markdown' }
      - { label: "Image", name: "image", widget: "image", required: false}
      - { label: "Visible", name: "visible", widget: "boolean", default: true}      
      - label: "Project"
        name: "project"
        widget: "select"
        required: false
        options: ["lorenzut", "practicar", "underpolished", "forhumansake", "radicallymarginal", "remotefaces"]
  - name: 'projects'
    label: 'Projects'
    format: 'json'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:      
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Last Updated', name: 'updated', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Content', name: 'content', widget: 'markdown' }
      - { label: "Visible", name: "visible", widget: "boolean", default: true}
      - { label: "Image", name: "image", widget: "image", required: false}
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }          
          - { label: 'URL', name: 'url', widget: 'string' }          
  - name: 'sections'
    label: 'Sections'
    format: 'json'
    folder: 'content/sections'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Intro', name: 'intro', widget: 'markdown' }
      - { label: 'Outro', name: 'outro', widget: 'markdown', required: false }      
      - label: "Expands"
        name: "expands"
        widget: "list"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }          
          - { label: 'Content', name: 'content', widget: 'markdown' }
          - { label: 'Link', name: 'link', widget: 'string', required: false }